# Generated by Django 5.1.3 on 2024-11-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_category_customer_product_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
